// <auto-generated />
using Lab2_AysncInn.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Lab2_AysncInn.Migrations
{
    [DbContext(typeof(AsyncInnContext))]
    [Migration("20230808161157_NewDatabaseAgain")]
    partial class NewDatabaseAgain
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Lab2_AysncInn.Models.Amenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Amenity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Name = "A/C"
                        },
                        new
                        {
                            ID = 2,
                            Name = "Free Wi-Fi"
                        },
                        new
                        {
                            ID = 3,
                            Name = "Swimming Pool"
                        });
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.Hotel", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Hotel");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Address = "123 Seasame St",
                            City = "Memphis",
                            Name = "Elmo Hotel",
                            Phone = "555-888-8888",
                            State = "TN"
                        },
                        new
                        {
                            ID = 2,
                            Address = "456 Oak St",
                            City = "New York",
                            Name = "Central Hotel",
                            Phone = "555-999-9999",
                            State = "NY"
                        },
                        new
                        {
                            ID = 3,
                            Address = "789 Pine St",
                            City = "Los Angeles",
                            Name = "Sunset Hotel",
                            Phone = "555-777-7777",
                            State = "CA"
                        });
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.HotelRoom", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("HotelID")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("HotelID");

                    b.HasIndex("RoomID");

                    b.ToTable("HotelRoom");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            HotelID = 1,
                            Price = 100.78,
                            RoomID = 1
                        },
                        new
                        {
                            ID = 2,
                            HotelID = 1,
                            Price = 150.99000000000001,
                            RoomID = 2
                        },
                        new
                        {
                            ID = 3,
                            HotelID = 3,
                            Price = 180.0,
                            RoomID = 3
                        });
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.Room", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("Layout")
                        .HasColumnType("int");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ID");

                    b.ToTable("Room");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            Layout = 0,
                            Name = "Basic Room"
                        },
                        new
                        {
                            ID = 2,
                            Layout = 1,
                            Name = "Deluxe Room"
                        },
                        new
                        {
                            ID = 3,
                            Layout = 2,
                            Name = "Suite Room"
                        });
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.RoomAmenity", b =>
                {
                    b.Property<int>("ID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ID"));

                    b.Property<int>("AmenityID")
                        .HasColumnType("int");

                    b.Property<int>("RoomID")
                        .HasColumnType("int");

                    b.HasKey("ID");

                    b.HasIndex("AmenityID");

                    b.HasIndex("RoomID");

                    b.ToTable("RoomAmenity");

                    b.HasData(
                        new
                        {
                            ID = 1,
                            AmenityID = 1,
                            RoomID = 1
                        },
                        new
                        {
                            ID = 2,
                            AmenityID = 2,
                            RoomID = 2
                        },
                        new
                        {
                            ID = 3,
                            AmenityID = 3,
                            RoomID = 3
                        });
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.HotelRoom", b =>
                {
                    b.HasOne("Lab2_AysncInn.Models.Hotel", "Hotel")
                        .WithMany("HotelRooms")
                        .HasForeignKey("HotelID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2_AysncInn.Models.Room", "Room")
                        .WithMany("hotelRooms")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Hotel");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.RoomAmenity", b =>
                {
                    b.HasOne("Lab2_AysncInn.Models.Amenity", "Amenity")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("AmenityID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Lab2_AysncInn.Models.Room", "Room")
                        .WithMany("RoomAmenities")
                        .HasForeignKey("RoomID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Amenity");

                    b.Navigation("Room");
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.Amenity", b =>
                {
                    b.Navigation("RoomAmenities");
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.Hotel", b =>
                {
                    b.Navigation("HotelRooms");
                });

            modelBuilder.Entity("Lab2_AysncInn.Models.Room", b =>
                {
                    b.Navigation("RoomAmenities");

                    b.Navigation("hotelRooms");
                });
#pragma warning restore 612, 618
        }
    }
}
